---
# handlers file for tooling
- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Restart php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: restarted
