- name: Clone the repository
  ansible.builtin.git:
   repo: https://github.com/Micah-Shallom/tooling.git
   clone: yes
   dest: /home/ec2-user/tooling
 
- name: copy the html from tooling to /var/www/html
  ansible.builtin.copy:
    src: /home/ec2-user/tooling/html/.
    dest: /var/www/html/
    mode: '0755'
    remote_src: yes

- name: create health status file
  ansible.builtin.file:
    path: /var/www/html/healthstatus
    state: touch

- name: Allow apache to modify /var/www/html
  community.general.sefcontext:
    target: /var/www/html/
    ignore_selinux_state: yes
    setype: httpd_sys_content_t
  notify: Restart httpd

